# Site settings
environment: development

title: Dead Rooster
description: > # this means to ignore newlines until "baseurl:"
  Le fantastique nouveau blog 2.0. Les anciens posts sont toujours disponibles
  sur <a href='http://deadrooster.org'>deadrooster.org</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
brand_logo: /assets/images/logo-dead-rooster-120.png
url: "http://blog-deadrooster-org.dev" # the base hostname & protocol for your site
twitter_username: dead__rooster
facebook_pagename: DeadRoosterBlog
github_url: "https://github.com/dirtyhenry/blog-deadrooster-org"
sass:
  style: compressed

# The postatic link has been disabled as it wasn't really used by anyone.
# postatic_url: "http://deadrooster.postatic.com"

# Build settings
markdown: kramdown

permalink: /:slug.html
exclude:
  [
    "node_modules",
    "Gemfile",
    "Gemfile.lock",
    "Gruntfile.js",
    "package.json",
    "package-lock.json",
    "README.md",
    "config.ru",
    "vendor",
    "Procfile",
    "unicorn.rb",
    "assets/images/s3",
    "Rakefile",
    "Makefile",
    "yarn.lock",
  ]

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap

theme: kids

# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true
