# Site settings
title: Dead Rooster
description: > # this means to ignore newlines until "baseurl:"
  Le fantastique nouveau blog 2.0. Les anciens posts sont toujours disponibles sur <a href='http://deadrooster.org'>deadrooster.org</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
brand_logo: /assets/images/logo-dead-rooster-120.png
url: "http://blog.deadrooster.org" # the base hostname & protocol for your site
twitter_username: dead__rooster
facebook_pagename: DeadRoosterBlog
destination: ~/Developer/build/blog-deadrooster-org-gh-pages
github_url: "https://github.com/dirtyhenry/blog-deadrooster-org"

# The postatic link has been disabled as it wasn't really used by anyone.
# postatic_url: "http://deadrooster.postatic.com"

# Build settings
markdown: kramdown

permalink:  /:title.html
exclude: [ 'bower_components', 'node_modules', 'bower.json', 'Gemfile', 'Gemfile.lock', 'Gruntfile.js', 'package.json', 'README.md', 'config.ru', 'vendor', 'Procfile', 'unicorn.rb', 'assets/images/s3', 'Rakefile' ]

gems:
  - jekyll-sitemap
