# Site settings
title: Dead Rooster
description: > # this means to ignore newlines until "baseurl:"
  Voici la nouvelle maison du blog culturo-sportivo-fun de Dead Rooster
  dont la version précédente est disponible sur l'ancienne adresse
  http://www.deadrooster.org 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.deadrooster.org" # the base hostname & protocol for your site
twitter_username: dead__rooster

# Build settings
markdown: kramdown

permalink:  /:title.html
exclude: [ 'bower_components', 'node_modules', 'bower.json', 'Gemfile', 'Gemfile.lock', 'Gruntfile.js', 'package.json', 'README.md', 'config.ru', 'vendor', 'Procfile', 'unicorn.rb']