# Site settings
title: Dead Rooster
description: > # this means to ignore newlines until "baseurl:"
  Le fantastique nouveau blog 2.0
baseurl: "" # the subpath of your site, e.g. /blog/
brand_logo: /assets/images/logo-dead-rooster-120.png
url: "http://blog.deadrooster.org" # the base hostname & protocol for your site
twitter_username: dead__rooster
facebook_pagename: DeadRoosterBlog
destination: ../blog-deadrooster-org-gh-pages

# Build settings
markdown: kramdown

permalink:  /:title.html
exclude: [ 'bower_components', 'node_modules', 'bower.json', 'Gemfile', 'Gemfile.lock', 'Gruntfile.js', 'package.json', 'README.md', 'config.ru', 'vendor', 'Procfile', 'unicorn.rb']